name: CI w/ Coverage Tests

on:
  pull_request: ~
  push: ~
  schedule:
    - cron: '42 5 * * 0'
  workflow_dispatch: ~

permissions:
  contents: read
  # actions: read is required to list artifacts via the API
  actions: read

jobs:

  freebsd:
    name: FreeBSD
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: '15.0'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"freebsd","os":"freebsd","arch":"x86_64","toolchain":"gcc","prepare":"pkg install -y perl5 lang/gcc"},
          {"platform_name":"freebsd","os":"freebsd","arch":"x86_64","toolchain":"clang","prepare":"pkg install -y perl5 llvm"},
          {"platform_name":"freebsd","os":"freebsd","arch":"aarch64","toolchain":"gcc","prepare":"pkg install -y perl5 lang/gcc"},
          {"platform_name":"freebsd","os":"freebsd","arch":"aarch64","toolchain":"clang","prepare":"pkg install -y perl5 llvm"}
        ]

  openbsd:
    name: OpenBSD
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: '7.8'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"openbsd","os":"openbsd","arch":"x86_64","toolchain":"egcc","prepare":"pkg_add gcc-11.2.0p19 g++-11.2.0p19"},
          {"platform_name":"openbsd","os":"openbsd","arch":"x86_64","toolchain":"clang"},
          {"platform_name":"openbsd","os":"openbsd","arch":"aarch64","toolchain":"egcc","prepare":"pkg_add gcc-11.2.0p19 g++-11.2.0p19"},
          {"platform_name":"openbsd","os":"openbsd","arch":"aarch64","toolchain":"clang"},
          {"platform_name":"openbsd","os":"openbsd","arch":"riscv64","toolchain":"egcc","prepare":"pkg_add gcc-11.2.0p19 g++-11.2.0p19"},
          {"platform_name":"openbsd","os":"openbsd","arch":"riscv64","toolchain":"clang"}
        ]
      #~ https://openbsd.app/

  netbsd:
    name: NetBSD
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: '10.1'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"netbsd","os":"netbsd","arch":"x86_64","toolchain":"gcc","prepare":"/usr/sbin/pkg_add perl"},
          {"platform_name":"netbsd","os":"netbsd","arch":"aarch64","toolchain":"gcc","prepare":"/usr/sbin/pkg_add perl"}
        ]

  dragonflybsd:
    name: DragonFly BSD
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: '6.4.0'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"dragonflybsd","os":"dragonflybsd","arch":"x86_64","toolchain":"gcc","prepare":"pkg install -y perl5 gcc"}
        ]

  solaris:
    name: Solaris
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: '11.4'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"solaris","os":"solaris","arch":"x86_64","toolchain":"gcc","prepare":"pkg install -v --accept perl-538 gcc"}
        ]

  omnios:
    name: OmniOS
    uses: ./.github/workflows/run-vm.yml
    secrets: inherit
    with:
      os_version: 'r151056'
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"omnios","os":"omnios","arch":"x86_64","toolchain":"gcc","prepare":"pkg install -v --accept perl build-essential"}
        ]

  linux:
    name: Linux
    uses: ./.github/workflows/run-direct.yml
    secrets: inherit
    with:
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"ubuntu","os":"ubuntu-latest","arch":"x86_64","toolchain":"gcc","prepare":"sudo apt-get update && sudo apt-get install -y gcc perl"},
          {"platform_name":"ubuntu","os":"ubuntu-latest","arch":"x86_64","toolchain":"clang","prepare":"sudo apt-get update && sudo apt-get install -y clang perl"},
          {"platform_name":"ubuntu","os":"ubuntu-24.04-arm","arch":"aarch64","toolchain":"gcc","prepare":"sudo apt-get update && sudo apt-get install -y gcc perl"},
          {"platform_name":"ubuntu","os":"ubuntu-24.04-arm","arch":"aarch64","toolchain":"clang","prepare":"sudo apt-get update && sudo apt-get install -y clang perl"},
          {"platform_name":"ubuntu","os":"ubuntu-24.04-riscv","arch":"riscv64","toolchain":"gcc","prepare":"sudo apt-get update && sudo apt-get install -y gcc perl"},
          {"platform_name":"ubuntu","os":"ubuntu-24.04-riscv","arch":"riscv64","toolchain":"clang","prepare":"sudo apt-get update && sudo apt-get install -y clang perl libclang-rt-dev"}
        ]

  macos:
    name: macOS
    uses: ./.github/workflows/run-direct.yml
    secrets: inherit
    with:
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"macos","os":"macos-15","arch":"aarch64","toolchain":"gcc"},
          {"platform_name":"macos","os":"macos-15","arch":"aarch64","toolchain":"clang"},
          {"platform_name":"macos","os":"macos-15-intel","arch":"x86_64","toolchain":"gcc"},
          {"platform_name":"macos","os":"macos-15-intel","arch":"x86_64","toolchain":"clang"}
        ]

  windows:
    name: Windows
    uses: ./.github/workflows/run-direct.yml
    secrets: inherit
    with:
      task: 'perl -V'
      matrix: >
        [
          {"platform_name":"windows","os":"windows-latest","arch":"x86_64","toolchain":"gcc","prepare":"choco install mingw strawberryperl"},
          {"platform_name":"windows","os":"windows-latest","arch":"x86_64","toolchain":"clang","prepare":"choco install llvm strawberryperl"},
          {"platform_name":"windows","os":"windows-latest","arch":"x86_64","toolchain":"msvc","prepare":"choco install opencppcoverage strawberryperl; bash"},
          {"platform_name":"windows","os":"windows-11-arm","arch":"aarch64","toolchain":"gcc"},
          {"platform_name":"windows","os":"windows-11-arm","arch":"aarch64","toolchain":"clang","prepare":"choco install llvm strawberryperl"},
          {"platform_name":"windows","os":"windows-11-arm","arch":"aarch64","toolchain":"msvc","prepare":"choco install opencppcoverage strawberryperl; bash"}
        ]
      # Setup Strawberry Perl so the task can invoke perl under bash

  results:
    name: Summary
    if: always()
    needs: [freebsd, openbsd, netbsd, dragonflybsd, solaris, omnios, linux, macos, windows]
    uses: ./.github/workflows/results-summary.yml

  publish-status:
    name: Publish Status Page
    if: ( success() || failure() ) && github.ref == 'refs/heads/main' # Only run on pushes to the main branch
    needs: [results]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: Permission to write to the repo (for gh-pages branch)
    steps:
      - name: Download status files
        #~ if: success() || failure()
        uses: actions/download-artifact@v8.0.1
        with:
          name: status-files
          path: ./status

      - name: Deploy to GitHub Pages
        #~ if: success() || failure()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./status
          publish_branch: gh-pages
          keep_files: true
          destination_dir: status
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Update build status matrix'
